inherits = "gruvbox"

"hint" = "blue"
"info" = "aqua"
"warning" = "yellow"
"error" = "red"
"comment" = "bg4"
"function" = "green"
"ui.bufferline" = { bg = "bg1" }
"ui.bufferline.active" = { bg = "bg1", modifiers = ["bold"] }
"ui.statusline.inactive" = { bg = "bg2" }

[palette]
green = "#b8bb26"

